name: License

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  license_check:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run licenses script
      run: bash ${GITHUB_WORKSPACE}/scripts/crates.sh --check
